BookingHotel/BookingHotel/Controllers/Manager/QLPhongController.cs
using BookingHotel.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingHotel.Controllers.Manager
{
    public class QLPhongController : Controller
    {
        // GET: Admin/QLPhong
       
        DBConnection db = new DBConnection();
        // GET: QLPhong
        public ActionResult Index()
        {
            return View();
        }
        // show Phong
        public ActionResult PhongR(int? page)
        {
            if (Session["LoginAD"] == null)
            {
                return RedirectToAction("Login", "Adminms");
            }
            else
            {
                int pageNum = (page ?? 1);
                int pageSize = 7;
                return View(db.Phongs.ToList().Where(a => a.Status == true && a.LoaiPhong.PStatus == true).OrderBy(x => x.maPhong).ToPagedList(pageNum, pageSize));
            }
        }

        public ActionResult CreateNew()
        {
            if (Session["LoginAD"] == null)
            {
                return RedirectToAction("Login", "Adminms");
            }
            else
            {
                Phong phong = new Phong();
                phong.listPhong = db.LoaiPhongs.Where(a => a.PStatus == true).ToList();
                return View(phong);
            }
        }
        [HttpPost]
        public ActionResult CreateNew(Phong phong, HttpPostedFileBase fileupload)
        {
            
            if (fileupload == null)
            {
                ViewBag.ThongBaoHinh = "Chọn ảnh phòng";
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var fileName = Path.GetFileName(fileupload.FileName);

                    var path = Path.Combine(Server.MapPath("~/images"), fileName);

                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                    }
                    else
                    {
                        fileupload.SaveAs(path);
                    }
                    phong.Image = fileName;
                    phong.tinhTrang = true;
                    phong.Status = true;
                    db.Phongs.Add(phong);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("PhongR");
        }
        // edit Phòng
        [HttpGet]
        public ActionResult EditPhongR(string id)
        {
            if (Session["LoginAD"] == null)
            {
                return RedirectToAction("Login", "Adminms");
            }
            else
            {
                Phong phong = new Phong();
                phong = db.Phongs.SingleOrDefault(a => a.maPhong == id);
                phong.listPhong = db.LoaiPhongs.Where(a => a.PStatus == true).ToList();
                return View(phong);
            }
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult EditPhongR(Phong phong, HttpPostedFileBase fileupload)
        {
            if (fileupload == null)
            {
                ViewBag.ThongBao = "Chọn ảnh món ăn";
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {

                    var fileName = Path.GetFileName(fileupload.FileName);

                    var path = Path.Combine(Server.MapPath("~/images"), fileName);

                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                    }
                    else
                    {
                        fileupload.SaveAs(path);
                    }
                    phong.Image = fileName;
                    phong.tinhTrang = true;
                    phong.Status = true;
                    db.Entry(phong).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("PhongR");
        }
        // xóa Phòng
        public ActionResult DeleteP(String id)
        {

            if (Session["LoginAD"] == null)
            {
                return RedirectToAction("Login", "Adminms");
            }
            else
            {
                Phong phong = db.Phongs.SingleOrDefault(a => a.maPhong == id);
                return View(phong);
            }

        }
        [HttpPost, ActionName("DeleteP")]
        public ActionResult XacNhanXoa(string id)
        {
            Phong phong = new Phong();
            phong = db.Phongs.SingleOrDefault(a => a.maPhong == id);
            if (phong == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            phong.Status = false;
            phong.tinhTrang = false;
            db.Entry(phong).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("PhongR");
        }

    }
    }

BookingHotel/BookingHotel/Views/QLPhong/CreateNew.cshtml
@model BookingHotel.Models.Phong
@{
    ViewBag.Title = "CreateNew";
    Layout = "~/Views/Shared/_MainAdmin.cshtml";
}

<h2>CreateNew</h2>
@using (Html.BeginForm("CreateNew", "QLPhong", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.maPhong, "Mã Phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maPhong, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.tenPhong, "Tên Phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, "Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="fileupload" />
                @*<img src="@Url.Content("~/images/"+ Model.Fimage)" width="250" height="200" /> (Ảnh hiện tại)*@
                @ViewBag.ThongBaoHinh
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Describe, "Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Describe, 10, 50, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Describe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giaPhong, "Giá Phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giaPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giaPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maLoai, "Loại phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownList("maLoai", new SelectList(Model.listPhong, "maLoai", "tenLoai"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.maLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm phòng" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay về danh sách phòng", "Phong")
</div>

BookingHotel/BookingHotel/Views/QLPhong/DeleteP.cshtml
@model BookingHotel.Models.Phong
@{
    ViewBag.Title = "DeleteP";
    Layout = "~/Views/Shared/_MainAdmin.cshtml";
}

<h3 style="color:red">Xác nhận xóa?</h3>
@Html.ActionLink("Quay về quản lý món", "PhongR")
<div>
    <hr />
    <dl class="dl-horizontal">
        @Html.HiddenFor(model => model.maPhong)
        <dt>
            Loại Phòng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiPhong.tenLoai)
        </dd>

        <dt>
            Tên Phòng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenPhong)
        </dd>

        <dt>
            Hình ảnh
        </dt>

        <dd>
            <img src="@Url.Content("~/images/"+Model.Image)" width="250" height="250" />

        </dd>

        <dt>
            Mô Tả Phòng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Describe)
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.FStatus)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FStatus)
            </dd>*@

        <dt>
            Giá Phòng
        </dt>

        <dd>
            @string.Format("{0:0,0}", Model.giaPhong) VNĐ
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">

            <input type="submit" value="Xóa Phòng" class="btn btn-warning" />

        </div>
    }
</div>

BookingHotel/BookingHotel/Views/QLPhong/EditPhongR.cshtml
@model BookingHotel.Models.Phong
@{
    ViewBag.Title = "EditPhongR";
    Layout = "~/Views/Shared/_MainAdmin.cshtml";
}


<div>
    @Html.ActionLink("Quay về quản lý Phòng", "PhongR")
</div>

@using (Html.BeginForm("EditPhongR", "QLPhong", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.maPhong)

        <div class="form-group">
            @Html.LabelFor(model => model.tenPhong, "Tên Phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenPhong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, "Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Fimage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fimage, "", new { @class = "text-danger" })*@
                <input type="file" name="fileupload" />
                <img src="@Url.Content("~/images/"+Model.Image)" width="250" height="250" /> (Ảnh hiện tại)

                @ViewBag.ThongBao
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Describe, "Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Describe, 5, 100, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Describe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giaPhong, "Giá Phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giaPhong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giaPhong, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.maLoai, "Loại Phòng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("maLoai", new SelectList(Model.listPhong, "maLoai", "tenLoai"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.maLoai, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu cập nhập" class="btn btn-danger" />
            </div>
        </div>
    </div>

    <div>
        @Html.ActionLink("Quay về danh sách phòng", "Phong")
    </div>

}

BookingHotel/BookingHotel/Views/QLPhong/PhongR.cshtml
@using BookingHotel.Models;
@using PagedList.Mvc;

@model PagedList.PagedList<BookingHotel.Models.Phong>
@{
    ViewBag.Title = "PhongR";
    Layout = "~/Views/Shared/_MainAdmin.cshtml";
}

@helper Truncate(string input, int length)
{
    if (input.Length < length || string.IsNullOrEmpty(input))
    {
        @input
    }
    else
    {
        @input.Substring(0, length) <text>...</text>
    }
}
<br />
<p>
    <button type="submit" class="btn btn-success" style="font-weight">@Html.ActionLink("Thêm phòng mới", "CreateNew")</button>
</p>
<table class="table" style="border-radius:10px">
    <tr style="background-color:lightgray">
        <th>
            <b><label>Loại Phòng</label></b>
        </th>
        <th>
            <b> <label>Tên Phòng</label></b>
        </th>
        <th>
            <b><label>Hình ảnh</label></b>
        </th>
        <th>
            <b> <label>Mô tả</label></b>
        </th>
        <th>
            <b><label>Giá Phòng</label></b>
        </th>
        <th></th>
    </tr>
    @{
        int row = 1;

    }
    @foreach (var item in Model)
    {
        <tr style="background-color:seashell; border-bottom-width:2px; border-style:solid; height:50px">
            <td>
                @Html.DisplayFor(modelItem => item.LoaiPhong.tenLoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tenPhong)
            </td>
            <td>
                <img src="@Url.Content("~/images/"+ item.Image)" height="100" width="100" />
            </td>
            <td id="content_@row">
                @Truncate(item.Describe, 50)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.FStatus)
                </td>*@
            <td>
                @string.Format("{0:0,0}", item.giaPhong)$
            </td>
            <td>
                @Html.ActionLink("Sửa", "EditPhongR", new { id = item.maPhong }) |
                @*@Html.ActionLink("Chi tiết", "DetailsFood", new { id = item.maPhong }) |*@
                @Html.ActionLink("Xóa", "DeleteP", new { id = item.maPhong })
            </td>
        </tr>
        row++;
    }
</table>

Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("PhongR", new { page = page }))
</div>

@*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div  style="display:flex">
        @Html.PagedListPager(Model, page => Url.Action("Phong", new { page = page }))
    </div>*@

<script>
    var index = @row;
    //function swaps() {

    //    for (let i = 1; i <= index; i++) {
    //        alert(i);
    //        if (document.getElementById("content_"+i).innerText.length > 2) {
    //            var swap = document.getElementById("content_"+i).innerText;
    //            swap = swap.slice(0, 2) + "...";
    //        }
    //    }

    //};

    //datatable
    $(function () {
        alert("1234")

    });
</script>