BookingHotel/BookingHotel/Controllers/BookingController.cs
using BookingHotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingHotel.Controllers
{
    public class BookingController : Controller
    {
        DBConnection db = new DBConnection();
        // GET: Booking
        public ActionResult IndexBooking(String id)
        {
            var Phong = db.Phongs.FirstOrDefault(p => p.maPhong.Equals(id));
            return View(Phong);
        }
        [HttpPost]
        public ActionResult addcart(FormCollection form, string id)
        {
            var tenKH = form["tenKH"];
            var hoKH = form["hoKH"];
            var Email = form["Email"];
            var Sdt = form["Sdt"];
            var diaChi = form["diaChi"];
            var ngayNhan = form["ngayNhan"];
            var ngayTra = form["ngayTra"];
            var soNguoi = form["soNguoi"];
            var Tongtien = form["Tongtien"];
           
                KhachHang KH = new KhachHang();
                PhieuDangKi DK = new PhieuDangKi();
                if ((db.KhachHangs.FirstOrDefault(p => p.Sdt.Equals(Sdt))) == null)
                {

                    KH.tenKH = hoKH + " " + tenKH;
                    KH.Email = Email;
                    KH.Sdt = Sdt;
                    KH.diaChi = diaChi;
                    db.KhachHangs.Add(KH);
                    DK.maNV = null;
                    DK.ngayNhan = (DateTime.Parse(ngayNhan));
                    DK.ngayDi = (DateTime.Parse(ngayTra));
                    DK.soNguoi = soNguoi;
                    DK.Tongtien = (int.Parse(Tongtien.Replace("$", "")));
                    DK.ngayLap = DateTime.Today;
                    DK.maKH = KH.maKH;
                    DK.Email = Email;
                    DK.xacNhan = false;
                    DK.trangThai = false;
                    DK.maPhong = id;
                    db.PhieuDangKis.Add(DK);
                    
                    
                }
                else {
                    DK.maNV = null;
                    DK.ngayNhan = (DateTime.Parse(ngayNhan));
                    DK.ngayDi = (DateTime.Parse(ngayTra));
                    DK.soNguoi = soNguoi;
                    DK.Tongtien = (int.Parse(Tongtien.Replace("$", "")));
                    DK.ngayLap = DateTime.Today;
                    DK.maKH = db.KhachHangs.FirstOrDefault(p => p.Sdt.Equals(Sdt)).maKH;
                    DK.xacNhan = false;
                    DK.Email = Email;
                    DK.trangThai = false;
                    DK.maPhong = id;
                    db.PhieuDangKis.Add(DK);
                }
            
            db.SaveChanges();
            TempData["thanhtoan"] = "Đặt phòng thành công";
            return RedirectToAction("IndexBooking",new { id = id});
        }
        
    }


}

BookingHotel/BookingHotel/Controllers/RoomController.cs
using BookingHotel.Models;
using BookingHotel.ObjectView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookingHotel.Controllers
{
    public class RoomController : Controller
    {
        DBConnection db = new DBConnection();
        // GET: Room
        public ActionResult Index(String name, String cate)
        {
            String add = name;
            String cate1 = cate;
            viewroom Room = new viewroom();
            if (String.IsNullOrEmpty(name) && String.IsNullOrEmpty(cate))
            {
                Room.lstRoom = db.Phongs.Where(p =>p.Status ==true && p.LoaiPhong.PStatus == true).ToList();
            }
            if (String.IsNullOrEmpty(name) && !String.IsNullOrEmpty(cate))
            {
                Room.lstRoom = db.Phongs.Where(p => p.maLoai.Equals(cate) && p.Status == true && p.LoaiPhong.PStatus == true).ToList();
            }
            if (!String.IsNullOrEmpty(name) && String.IsNullOrEmpty(cate))
            {
                Room.lstRoom = db.Phongs.Where(p => p.tenPhong.Contains(name) && p.Status == true && p.LoaiPhong.PStatus == true).ToList();
            }
            if (!String.IsNullOrEmpty(name) && !String.IsNullOrEmpty(cate))
            {
                Room.lstRoom = db.Phongs.Where(p => p.maLoai.Equals(cate) && p.tenPhong.Contains(name) && p.Status == true && p.LoaiPhong.PStatus == true).ToList();
            }
            Room.lstcateRoom = db.LoaiPhongs.ToList();
            return View(Room);
        }
        public ActionResult Search(FormCollection form)
        {
            var name = form["searchbox"];
            var cate = form.Get("searchcate");
            return RedirectToAction("index", new { name = name, cate = cate });
        }
        //detail room
        public ActionResult Detail(String id)
        {
            var roomDetail = from s in db.Phongs
                             where s.maPhong.Equals(id)
                             select s;
            return View(roomDetail.SingleOrDefault());
        }
    }
}

BookingHotel/BookingHotel/Views/Room/Detail.cshtml
@model BookingHotel.Models.Phong
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!DOCTYPE HTML>
<html>
<head>
    <link href="~/assetdetail/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/assetdetail/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <script src="~/assetdetail/js/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".dropdown img.flag").addClass("flagvisibility");

            $(".dropdown dt a").click(function () {
                $(".dropdown dd ul").toggle();
            });

            $(".dropdown dd ul li a").click(function () {
                var text = $(this).html();
                $(".dropdown dt a span").html(text);
                $(".dropdown dd ul").hide();
                $("#result").html("Selected value is: " + getSelectedValue("sample"));
            });

            function getSelectedValue(id) {
                return $("#" + id).find("dt a span.value").html();
            }

            $(document).bind('click', function (e) {
                var $clicked = $(e.target);
                if (!$clicked.parents().hasClass("dropdown"))
                    $(".dropdown dd ul").hide();
            });


            $("#flagSwitcher").click(function () {
                $(".dropdown img.flag").toggleClass("flagvisibility");
            });
        });
    </script>
    <!----details-product-slider--->
    <!-- Include the Etalage files -->
    <link rel="stylesheet" href="~/assetdetail/css/etalage.css">
    <script src="~/assetdetail/js/jquery.etalage.min.js"></script>
    <!-- Include the Etalage files -->
    <script>
        jQuery(document).ready(function ($) {

            $('#etalage').etalage({
                thumb_image_width: 300,
                thumb_image_height: 400,

                show_hint: true,
                click_callback: function (image_anchor, instance_id) {
                    alert('Callback example:\nYou clicked on an image with the anchor: "' + image_anchor + '"\n(in Etalage instance: "' + instance_id + '")');
                }
            });
            // This is for the dropdown list example:
            $('.dropdownlist').change(function () {
                etalage_show($(this).find('option:selected').attr('class'));
            });

        });
    </script>
    <!----//details-product-slider--->
</head>
<body>
    <div class="main">
        <div class="shop_top">
            <div class="container">
                <div class="row">
                    <div class="col-md-9 single_left">
                        <div class="single_image">
                            <ul id="etalage">
                                <li>
                                    <a href="optionallink.html">
                                        <img class="etalage_thumb_image" src="@Url.Content("~/images/"+ Model.Image)" width="300" height="300" />
                                        <img class="etalage_source_image" src="@Url.Content("~/images/"+ Model.Image)" height="300" width="300" />
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- end product_slider -->
                        <div class="single_right">
                            <h3>@Model.tenPhong </h3>
                            <p class="m_10">@Model.Describe</p>
                           
                            
                            <div class="social_buttons">
                                <h4>95 Items</h4>
                                <button type="button" class="btn1 btn1-default1 btn1-twitter">
                                    <i class="icon-twitter"></i> Twitter
                                </button>
                                <button type="button" class="btn1 btn1-default1 btn1-facebook" onclick="">
                                    <i class="icon-facebook"></i> FaceBook
                                </button>
                                <button type="button" class="btn1 btn1-default1 btn1-google" onclick="">
                                    <i class="icon-google"></i> Google
                                </button>
                                <button type="button" class="btn1 btn1-default1 btn1-pinterest" onclick="">
                                    <i class="icon-pinterest"></i> Pinterest
                                </button>
                            </div>
                        </div>
                        <div class="clear"> </div>
                    </div>
                    <div class="col-md-3">
                        <div class="box-info-product">
                            <p class="price2">$@Model.giaPhong</p>
                            <a type="button" href="@Url.Action("IndexBooking","Booking", new { id = Model.maPhong })" name="Submit" class="exclusive">
                                <span>Booking</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="desc">
                    @*<h4>Description</h4>
                    <p><b>@Model.Describe</b></p>*@
                    
                </div>
                @*<div class="row">
                    <h4 class="m_11">Related Products in the same Category</h4>
                    <div class="col-md-4 product1">
                        <img src="~/assetdetail/images/s1.jpg" class="img-responsive" alt="" />
                        <div class="shop_desc">
                            <a href="single.html">
                            </a><h3><a href="single.html"></a><a href="#">aliquam volutp</a></h3>
                            <p>Lorem ipsum consectetuer adipiscing </p>
                            <span class="reducedfrom">$66.00</span>
                            <span class="actual">$12.00</span><br>
                            <ul class="buttons">
                                <li class="cart"><a href="#">Add To Cart</a></li>
                                <li class="shop_btn"><a href="#">Read More</a></li>
                                <div class="clear"> </div>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4 product1">
                        <img src="~/assetdetail/images/s2.jpg" class="img-responsive" alt="" />
                        <div class="shop_desc">
                            <a href="single.html">
                            </a><h3><a href="single.html"></a><a href="#">aliquam volutp</a></h3>
                            <p>Lorem ipsum consectetuer adipiscing </p>
                            <span class="reducedfrom">$66.00</span>
                            <span class="actual">$12.00</span><br>
                            <ul class="buttons">
                                <li class="cart"><a href="#">Add To Cart</a></li>
                                <li class="shop_btn"><a href="#">Read More</a></li>
                                <div class="clear"> </div>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <img src="~/assetdetail/images/s3.jpg" class="img-responsive" alt="" />
                        <div class="shop_desc">
                            <a href="single.html">
                            </a><h3><a href="single.html"></a><a href="#">aliquam volutp</a></h3>
                            <p>Lorem ipsum consectetuer adipiscing </p>
                            <span class="reducedfrom">$66.00</span>
                            <span class="actual">$12.00</span><br>
                            <ul class="buttons">
                                <li class="cart"><a href="#">Add To Cart</a></li>
                                <li class="shop_btn"><a href="#">Read More</a></li>
                                <div class="clear"> </div>
                            </ul>
                        </div>
                    </div>
                </div>*@
            </div>
        </div>
    </div>
    
</body>
</html>

BookingHotel/BookingHotel/Views/Room/Index.cshtml
@model BookingHotel.ObjectView.viewroom
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}



<section class="section pb-4">
    <div class="container">

        <div class="row check-availabilty" id="next">
            <div class="block-32" data-aos="fade-up" data-aos-offset="-200" style="margin-bottom: 10px">
                @using (Html.BeginForm())
                {


                    <div class="row">

                        <input type="text" placeholder="search..." name="searchbox" class="form-control" style="width:50%">
                        <label style="padding-top:5px; margin-left:2%" class="font-weight-bold text-black">Room Types</label>
                        <select style="width:16%; margin-left:2%" name="searchcate" class="form-control">
                            <option></option>
                            @foreach (var item in Model.lstcateRoom)
                            {
                                <option value="@item.maLoai">@item.tenLoai</option>
                            }
                        </select>

                        <input type="submit" formaction="@Url.Action("Search","Room")" class="btn btn-danger" value="Search" style="width:16%; margin-left:2%" />
                    </div>
                }
            </div>

        </div>
    </div>
</section>

<section class="section">
    <div class="container">

        <div class="row">
            @foreach (var item in Model.lstRoom)
            {
                <div class="col-md-6 col-lg-4 mb-5" data-aos="fade-up">
                    <a href="@Url.Action("Detail",new {id= @item.maPhong})" class="room">
                        <figure class="img-wrap">
                            <img style="display:block; margin-left:auto;margin-right:auto " src="@Url.Content("~/images/"+ item.Image)" height="320" width="300" />
                            @*<img src=@item.Image alt="Free website template" class="img-fluid mb-3">*@
                        </figure>
                        <div class="p-3 text-center room-info">
                            <h2>@item.tenPhong</h2>
                            <span class="text-uppercase letter-spacing-1">$@item.giaPhong / per night</span>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</section>

@Html.Partial("_Top2", BookingHotel.Models.Top.Showtop.Top2())
@*<script src="/Asset/js/jquery-3.3.1.min.js"></script>
    <script src="/Asset/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="/Asset/js/popper.min.js"></script>
    <script src="/Asset/js/bootstrap.min.js"></script>
    <script src="/Asset/js/owl.carousel.min.js"></script>
    <script src="/Asset/js/jquery.stellar.min.js"></script>
    <script src="/Asset/js/jquery.fancybox.min.js"></script>


    <script src="/Asset/js/aos.js"></script>

    <script src="/Asset/js/bootstrap-datepicker.js"></script>
    <script src="/Asset/js/jquery.timepicker.min.js"></script>

    <script src="/Asset/js/main.js"></script>*@